const ancientsContainer = document.querySelector('.container-ancients-cards'),
    ancient1 = document.querySelector('#ancient-1'),
    ancient2 = document.querySelector('#ancient-2'),
    ancient3 = document.querySelector('#ancient-3'),
    ancient4 = document.querySelector('#ancient-4'),
    stageVlalue11 = document.querySelector('#stage-value-1-1'),
    stageVlalue12 = document.querySelector('#stage-value-1-2'),
    stageVlalue13 = document.querySelector('#stage-value-1-3'),
    stageVlalue21 = document.querySelector('#stage-value-2-1'),
    stageVlalue22 = document.querySelector('#stage-value-2-2'),
    stageVlalue23 = document.querySelector('#stage-value-2-3'),
    stageVlalue31 = document.querySelector('#stage-value-3-1'),
    stageVlalue32 = document.querySelector('#stage-value-3-2'),
    stageVlalue33 = document.querySelector('#stage-value-3-3'),
    difficultyButtons = document.querySelectorAll('.difficulty-button'),
    difficulty1 = document.querySelector('#difficulty-1'),
    difficulty2 = document.querySelector('#difficulty-2'),
    difficulty3 = document.querySelector('#difficulty-3'),
    difficulty4 = document.querySelector('#difficulty-4'),
    difficulty5 = document.querySelector('#difficulty-5'),
    deck = document.querySelector('#deck'),
    current = document.querySelector('#current');




export {
    ancientsContainer,
    ancient1,
    ancient2,
    ancient3,
    ancient4,
    stageVlalue11,
    stageVlalue12,
    stageVlalue13,
    stageVlalue21,
    stageVlalue22,
    stageVlalue23,
    stageVlalue31,
    stageVlalue32,
    stageVlalue33,
    difficultyButtons,
    difficulty1,
    difficulty2,
    difficulty3,
    difficulty4,
    difficulty5,
    deck,
    current,

};