const ancientsContainer = document.querySelector('.container-ancients-cards'),
    ancient1 = document.querySelector('#ancient-1'),
    ancient2 = document.querySelector('#ancient-2'),
    ancient3 = document.querySelector('#ancient-3'),
    ancient4 = document.querySelector('#ancient-4'),
    tracker = document.querySelector('.tracker'),
    stageValues = document.querySelectorAll('.stage-value'),
    stage1Green = document.querySelector('#stage-1-green'),
    stage1Brown = document.querySelector('#stage-1-brown'),
    stage1Blue = document.querySelector('#stage-1-blue'),
    stage2Green = document.querySelector('#stage-2-green'),
    stage2Brown = document.querySelector('#stage-2-brown'),
    stage2Blue = document.querySelector('#stage-2-blue'),
    stage3Green = document.querySelector('#stage-3-green'),
    stage3Brown = document.querySelector('#stage-3-brown'),
    stage3Blue = document.querySelector('#stage-3-blue'),
    difficultyContainer = document.querySelector('.container-difficulty'),
    difficultyButtons = document.querySelectorAll('.difficulty-button'),
    difficulty1 = document.querySelector('#difficulty-1'),
    difficulty2 = document.querySelector('#difficulty-2'),
    difficulty3 = document.querySelector('#difficulty-3'),
    difficulty4 = document.querySelector('#difficulty-4'),
    difficulty5 = document.querySelector('#difficulty-5'),
    deckTitle = document.querySelector('#deck-title'),
    deck = document.querySelector('#deck'),
    current = document.querySelector('#current');

export {
    ancientsContainer,
    ancient1,
    ancient2,
    ancient3,
    ancient4,
    tracker,
    stageValues,
    stage1Green,
    stage1Brown,
    stage1Blue,
    stage2Green,
    stage2Brown,
    stage2Blue,
    stage3Green,
    stage3Brown,
    stage3Blue,
    difficultyContainer,
    difficultyButtons,
    difficulty1,
    difficulty2,
    difficulty3,
    difficulty4,
    difficulty5,
    deckTitle,
    deck,
    current,
};